FROM golang:1.16.5-alpine as builder

RUN apk update \
 && apk add --no-cache git \
 && go env -w GOPROXY=direct

WORKDIR /work/app

COPY src/app .
RUN rm -f go.mod go.sum \
 && go mod init app \
 && go mod tidy \
 && go build -o /main


FROM alpine:3.14.2
COPY --from=builder /main /main
ENV LOG_LEVEL=2
WORKDIR /

ENTRYPOINT [ "/main"]
